using RevivalGF.Entites.Concrete;
using RevivalGF.Entites.Enums;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using RevivalGF.Entites.Abstract;

namespace RevivalGF.DataAccess.Context
{
    public class MealDbInitializer<T> : CreateDatabaseIfNotExists<RevivalGfDbContext>
    {
        protected override void Seed(RevivalGfDbContext context)
        {
            IList<Meal> meals = new List<Meal>();

            meals.Add(new Meal() { MealName = "Beans", Calorie = 400M, Carbonhydrade = 14M, Fat = 0.8M, Protein = 7.4M, Gram = 250, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Beets", Calorie = 22M, Carbonhydrade = 5.0M, Fat = 0.1M, Protein = 0.8M, Gram = 50, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Bok Choy", Calorie = 380M, Carbonhydrade = 2.2M, Fat = 0.2M, Protein = 1.5M, Gram = 200, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Broccoli", Calorie = 340M, Carbonhydrade = 6.64M, Fat = 0.37M, Protein = 2.82M, Gram = 250, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Cabbage", Calorie = 35M, Carbonhydrade = 8.3M, Fat = 0.1M, Protein = 1.9M, Gram = 150, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Carrots", Calorie = 16M, Carbonhydrade = 3.8M, Fat = 0.1M, Protein = 0.3M, Gram = 45, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Cauliflower", Calorie = 29M, Carbonhydrade = 5.1M, Fat = 0.6M, Protein = 2.3M, Gram = 125, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Celeriac", Calorie = 42M, Carbonhydrade = 9.1M, Fat = 0.3M, Protein = 1.5M, Gram = 150, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Chickpeas", Calorie = 269M, Carbonhydrade = 45M, Fat = 4.2M, Protein = 14.5M, Gram = 164, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Corn", Calorie = 123M, Carbonhydrade = 26.7M, Fat = 1.9M, Protein = 4.7M, Gram = 145, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Cowpeas", Calorie = 81M, Carbonhydrade = 14.5M, Fat = 0.4M, Protein = 5.4M, Gram = 70, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Cucumber", Calorie = 50M, Carbonhydrade = 3.63M, Fat = 0.11M, Protein = 0.65M, Gram = 50, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Cup Mushrooms", Calorie = 350M, Carbonhydrade = 4.1M, Fat = 0.1M, Protein = 2.5M, Gram = 280, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Eggplant", Calorie = 400M, Carbonhydrade = 5.88M, Fat = 0.18M, Protein = 0.98M, Gram = 250, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Gourd", Calorie = 100M, Carbonhydrade = 25.5M, Fat = 0.6M, Protein = 1.2M, Gram = 180, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Leeks", Calorie = 38M, Carbonhydrade = 9.4M, Fat = 0.2M, Protein = 1.0M, Gram = 125, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Lentils", Calorie = 678M, Carbonhydrade = 120.6M, Fat = 3.2M, Protein = 49.5M, Gram = 192, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Lettuce", Calorie = 23M, Carbonhydrade = 4.3M, Fat = 0.2M, Protein = 2.0M, Gram = 150, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Okra", Calorie = 35M, Carbonhydrade = 7.2M, Fat = 0.3M, Protein = 3.0M, Gram = 160, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Onion", Calorie = 7M, Carbonhydrade = 1.5M, Fat = 0.1M, Protein = 0.4M, Gram = 40, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Peas", Calorie = 134M, Carbonhydrade = 25.0M, Fat = 0.4M, Protein = 8.6M, Gram = 160, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Red Capcicum", Calorie = 60M, Carbonhydrade = 4.64M, Fat = 0.17M, Protein = 0.86M, Gram = 60, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Spinach", Calorie = 310M, Carbonhydrade = 3.6M, Fat = 0.4M, Protein = 2.9M, Gram = 250, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Sweet Potato", Calorie = 420M, Carbonhydrade = 20.1M, Fat = 0.1M, Protein = 1.6M, Gram = 300, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Yellow Beans", Calorie = 255M, Carbonhydrade = 44.7M, Fat = 1.9M, Protein = 16.2M, Gram = 177, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });

            meals.Add(new Meal() { MealName = "Butter, light", Calorie = 70M, Carbonhydrade = 0M, Fat = 7.7M, Protein = 0.5M, Gram = 14, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.MilkAndDairyProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Cheddar Cheese", Calorie = 113M, Carbonhydrade = 0.9M, Fat = 9.3M, Protein = 6.4M, Gram = 28, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.MilkAndDairyProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Chocolate Pudding", Calorie = 213M, Carbonhydrade = 34.5M, Fat = 6.9M, Protein = 3.1M, Gram = 150, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.MilkAndDairyProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Chocolate Pudding, fat free", Calorie = 105M, Carbonhydrade = 23.6M, Fat = 0.3M, Protein = 2.2M, Gram = 113, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.MilkAndDairyProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Chocolate Yogurt", Calorie = 168M, Carbonhydrade = 35.3M, Fat = 0M, Protein = 5.3M, Gram = 150, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.MilkAndDairyProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Cottage Cheese, low fat", Calorie = 163M, Carbonhydrade = 6.1M, Fat = 2.3M, Protein = 28.0M, Gram = 226, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.MilkAndDairyProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Cottage Cheese, nonfat", Calorie = 104M, Carbonhydrade = 9.7M, Fat = 0.4M, Protein = 15.0M, Gram = 145, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.MilkAndDairyProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Cream Cheese", Calorie = 51M, Carbonhydrade = 0.8M, Fat = 5.0M, Protein = 0.9M, Gram = 14.5M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.MilkAndDairyProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Frozen Yogurt", Calorie = 221M, Carbonhydrade = 37.6M, Fat = 6.3M, Protein = 5.2M, Gram = 174, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.MilkAndDairyProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Fruit Yogurt", Calorie = 149M, Carbonhydrade = 28.0M, Fat = 1.7M, Protein = 6.0M, Gram = 150, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.MilkAndDairyProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Goat Cheese", Calorie = 128M, Carbonhydrade = 0.6M, Fat = 10.1M, Protein = 8.6M, Gram = 28.3M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.MilkAndDairyProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Vanilla Pudding", Calorie = 195M, Carbonhydrade = 33.9M, Fat = 5.7M, Protein = 2.2M, Gram = 150, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.MilkAndDairyProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Yogurt", Calorie = 92M, Carbonhydrade = 7.0M, Fat = 4.9M, Protein = 5.2M, Gram = 150, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.MilkAndDairyProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Yogurt Parfait", Calorie = 125M, Carbonhydrade = 23.6M, Fat = 1.5M, Protein = 5.0M, Gram = 149, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.MilkAndDairyProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Yogurt, low fat", Calorie = 154M, Carbonhydrade = 17.2M, Fat = 3.8M, Protein = 12.9M, Gram = 245, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.MilkAndDairyProducts, ServiceType = ServiceType.Portion });

            meals.Add(new Meal() { MealName = "Apple", Calorie = 95M, Carbonhydrade = 25.1M, Fat = 0.3M, Protein = 0.5M, Gram = 182M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Fruits, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Apricot", Calorie = 17M, Carbonhydrade = 3.9M, Fat = 0.1M, Protein = 0.5M, Gram = 35M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Fruits, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Banana", Calorie = 134M, Carbonhydrade = 34.3M, Fat = 0.5M, Protein = 1.6M, Gram = 150M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Fruits, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Blackberries", Calorie = 62M, Carbonhydrade = 13.8M, Fat = 0.7M, Protein = 2.0M, Gram = 144M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Fruits, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Blueberries", Calorie = 84M, Carbonhydrade = 21.4M, Fat = 0.5M, Protein = 1.1M, Gram = 148M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Fruits, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Cherrie", Calorie = 52M, Carbonhydrade = 12.5M, Fat = 0.3M, Protein = 0.1M, Gram = 8M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Fruits, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Figs", Calorie = 37M, Carbonhydrade = 9.6M, Fat = 1.0M, Protein = 1.7M, Gram = 243M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Fruits, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Grapefruit", Calorie = 53M, Carbonhydrade = 13.3M, Fat = 0.2M, Protein = 1.0M, Gram = 125M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Fruits, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Grapes", Calorie = 3M, Carbonhydrade = 0.9M, Fat = 0.1M, Protein = 0.1M, Gram = 5M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Fruits, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Mango", Calorie = 202M, Carbonhydrade = 50.3M, Fat = 1.3M, Protein = 2.8M, Gram = 336M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Fruits, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Orange", Calorie = 86M, Carbonhydrade = 21.6M, Fat = 0.2M, Protein = 1.7M, Gram = 184M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Fruits, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Pineapple", Calorie = 45M, Carbonhydrade = 11.8M, Fat = 0.1M, Protein = 0.5M, Gram = 90M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Fruits, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Plum", Calorie = 30M, Carbonhydrade = 7.5M, Fat = 0.2M, Protein = 0.5M, Gram = 66M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Fruits, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Pomegranate", Calorie = 117M, Carbonhydrade = 26.4M, Fat = 1.6M, Protein = 2.4M, Gram = 141M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Fruits, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Raspberries", Calorie = 5M, Carbonhydrade = 1.2M, Fat = 0.1M, Protein = 0.1M, Gram = 10M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Fruits, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Strawberries", Calorie = 4M, Carbonhydrade = 0.9M, Fat = 0.1M, Protein = 0.1M, Gram = 12M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Fruits, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Tangerine", Calorie = 40M, Carbonhydrade = 10.1M, Fat = 0.2M, Protein = 0.6M, Gram = 76M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Fruits, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Watermelon", Calorie = 86M, Carbonhydrade = 21.6M, Fat = 0.4M, Protein = 1.7M, Gram = 286M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Fruits, ServiceType = ServiceType.Piece });

            meals.Add(new Meal() { MealName = "Anchovy", Calorie = 37M, Carbonhydrade = 0M, Fat = 1.4M, Protein = 5.8M, Gram = 29M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.FishProducts, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Bass", Calorie = 90M, Carbonhydrade = 0M, Fat = 2.9M, Protein = 14.9M, Gram = 79M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.FishProducts, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Bluefish", Calorie = 186M, Carbonhydrade = 0M, Fat = 6.4M, Protein = 30.1M, Gram = 117M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.FishProducts, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Fish Fillet", Calorie = 211M, Carbonhydrade = 15.4M, Fat = 11.2M, Protein = 13.3M, Gram = 91M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.FishProducts, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Haddock", Calorie = 143M, Carbonhydrade = 0M, Fat = 0.9M, Protein = 31.5M, Gram = 193M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.FishProducts, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Salmon", Calorie = 474M, Carbonhydrade = 0M, Fat = 14.9M, Protein = 79.5M, Gram = 308M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.FishProducts, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Sardine", Calorie = 310M, Carbonhydrade = 0M, Fat = 17.1M, Protein = 36.7M, Gram = 149M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.FishProducts, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Sea Bass", Calorie = 125M, Carbonhydrade = 0M, Fat = 2.6M, Protein = 23.9M, Gram = 101M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.FishProducts, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Shrimp", Calorie = 128M, Carbonhydrade = 0M, Fat = 1.7M, Protein = 26.1M, Gram = 128M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.FishProducts, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Whiting", Calorie = 84M, Carbonhydrade = 0M, Fat = 1.2M, Protein = 16.9M, Gram = 72M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.FishProducts, ServiceType = ServiceType.Piece });

            meals.Add(new Meal() { MealName = "Apple Pie", Calorie = 331M, Carbonhydrade = 46.4M, Fat = 15.6M, Protein = 3.0M, Gram = 125M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.BakeryProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Banana Cream Pie", Calorie = 319M, Carbonhydrade = 390.2M, Fat = 161.3M, Protein = 52.2M, Gram = 1186M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.BakeryProducts, ServiceType = ServiceType.Portion });

            meals.Add(new Meal() { Recipe = "Rice Flour Cake\r\n2 eggs\r\n1 glass of sugar\r\n1 cup of sunflower oil\r\n1 glass of water Milk\r\n2.5 cups rice flour\r\n1 packet of vanilla\r\n1 packet of baking powder\r\n1 tablespoon of cocoa\r\nBeat the eggs. Add the sugar and beat until opaque. Add oil and milk respectively and mix. Add the vanilla and baking powder to the mixture along with the rice flour and mix. Pour ¾ of the cake batter into the greased cake mold. Mix cocoa into the remaining mortar. Pour this mixture over the plain cake batter.\r\nBake at 170°C for 35-40 minutes.\r\n", MealName = "Rice Flour Cake", Calorie = 252M, Carbonhydrade = 40.7M, Fat = 13.2M, Protein = 4.2M, Gram = 103M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.BakeryProducts, ServiceType = ServiceType.Portion });

            meals.Add(new Meal() { MealName = "Donut", Calorie = 192M, Carbonhydrade = 22.9M, Fat = 10.3M, Protein = 2.3M, Gram = 45M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.BakeryProducts, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Fruitcake", Calorie = 139M, Carbonhydrade = 26.5M, Fat = 3.9M, Protein = 1.2M, Gram = 43M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.BakeryProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Gingerbread", Calorie = 263M, Carbonhydrade = 36.4M, Fat = 12.1M, Protein = 2.9M, Gram = 74M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.BakeryProducts, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { Recipe = "Gluten Free Brownie \r\nMaterials: \r\ngluten free flour \r\n2 cups sugar \r\n125 gr. butter \r\n3 eggs \r\n2 soup spoons of cocoa \r\n1 packet of vanilla \r\n1 cup crushed walnuts \r\n250 gr. dark chocolate \r\nMelt the butter and chocolate in a bain-marie and add the cocoa. In a separate bowl, beat the eggs and sugar until creamy. Add the chocolate mixture. Add the gluten-free flour and vanilla and continue mixing. Finally, add the crushed walnuts and put the whole mixture on a baking tray lined with greaseproof paper. Bake in a preheated 180°C oven for 25 minutes. Your gluten-free brownie is ready; enjoy your meal!\r\n", MealName = "Gluten Free Brownie ", Calorie = 230M, Carbonhydrade = 30.7M, Fat = 7.3M, Protein = 2.4M, Gram = 58M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.BakeryProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { Recipe = "Gluten Free Cheesecake \r\nMaterials: \r\n6 Pronot gluten-free biscuits \r\n1 tablespoon of milk \r\n1 pack of labneh cheese \r\n2 tablespoons of honey \r\n1 teaspoon lemon juice \r\n2 handfuls of frozen blackberries \r\nPass the Pronot gluten-free biscuits through the mixer, mix with milk and pour into two glasses to distribute it equally. Mix labneh, honey and lemon juice and distribute it over the biscuits in the glasses. Finally, garnish the glasses with frozen berries. This gluten-free cheesecake that you will prepare for two people is both delicious and practical! With pleasure...\r\n", MealName = "Gluten Free Cheesecake ", Calorie = 250M, Carbonhydrade = 17.2M, Fat = 15.6M, Protein = 4.3M, Gram = 74M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.BakeryProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Muffin", Calorie = 169M, Carbonhydrade = 23.6M, Fat = 6.5M, Protein = 3.9M, Gram = 57M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.BakeryProducts, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Semolina", Calorie = 601M, Carbonhydrade = 121.6M, Fat = 1.8M, Protein = 21.2M, Gram = 167M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.BakeryProducts, ServiceType = ServiceType.Portion });


            meals.Add(new Meal() { MealName = "Chocolate", Calorie = 208M, Carbonhydrade = 24.8M, Fat = 14.0M, Protein = 1.6M, Gram = 41M, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.Snacks, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Dark Chocolate", Calorie = 165M, Carbonhydrade = 18.0M, Fat = 9.7M, Protein = 1.5M, Gram = 30M, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.Snacks, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Hazelnuts, blanched", Calorie = 178M, Carbonhydrade = 4.8M, Fat = 17.3M, Protein = 3.9M, Gram = 29M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Snacks, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Hazelnuts, raw", Calorie = 471M, Carbonhydrade = 12.5M, Fat = 45.6M, Protein = 11.2M, Gram = 75M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Snacks, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Hazelnuts, roasted", Calorie = 194M, Carbonhydrade = 5.3M, Fat = 18.7M, Protein = 4.5M, Gram = 30M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Snacks, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Peanut Butter Cookie Protein", Calorie = 200M, Carbonhydrade = 15.0M, Fat = 6.0M, Protein = 22.0M, Gram = 47M, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.Snacks, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Peanuts", Calorie = 828M, Carbonhydrade = 23.5M, Fat = 71.9M, Protein = 37.7M, Gram = 145M, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.Snacks, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Pistachio Nuts, raw", Calorie = 691M, Carbonhydrade = 33.8M, Fat = 55.8M, Protein = 24.9M, Gram = 125M, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.Snacks, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Pistachio Nuts, roasted", Calorie = 172M, Carbonhydrade = 8.5M, Fat = 13.7M, Protein = 6.3M, Gram = 30M, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.Snacks, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Walnut", Calorie = 33M, Carbonhydrade = 0.7M, Fat = 3.3M, Protein = 0.8M, Gram = 5M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Snacks, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "White Chocolate", Calorie = 162M, Carbonhydrade = 17.8M, Fat = 9.6M, Protein = 1.8M, Gram = 30M, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.Snacks, ServiceType = ServiceType.Piece });

            meals.Add(new Meal() { MealName = "Apple Juice", Calorie = 114M, Carbonhydrade = 28.0M, Fat = 0.3M, Protein = 0.2M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Black Tea", Calorie = 5M, Carbonhydrade = 0.7M, Fat = 0M, Protein = 0M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Carrot Juice", Calorie = 85M, Carbonhydrade = 18.7M, Fat = 0.4M, Protein = 1.9M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Chocolate Milk", Calorie = 208M, Carbonhydrade = 25.9M, Fat = 8.5M, Protein = 7.9M, Gram = 0, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Coconut Milk", Calorie = 40M, Carbonhydrade = 0.9M, Fat = 3.7M, Protein = 0.4M, Gram = 0, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Coffee", Calorie = 25M, Carbonhydrade = 0M, Fat = 0.2M, Protein = 0.4M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Cola", Calorie = 95M, Carbonhydrade = 19.1M, Fat = 0.2M, Protein = 0.2M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Cola Light", Calorie = 0M, Carbonhydrade = 0M, Fat = 0M, Protein = 0M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Energy Drink", Calorie = 111M, Carbonhydrade = 26.4M, Fat = 0.0M, Protein = 1.2M, Gram = 0, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Energy Drink, sugar-free", Calorie = 13M, Carbonhydrade = 1.8M, Fat = 0.2M, Protein = 0.6M, Gram = 0, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Freshly Squeezed Juice", Calorie = 140M, Carbonhydrade = 29.5M, Fat = 0M, Protein = 0.46M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Fruit Juice", Calorie = 158M, Carbonhydrade = 26.5M, Fat = 0.2M, Protein = 0.4M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Goat Milk", Calorie = 170M, Carbonhydrade = 11.2M, Fat = 10.2M, Protein = 8.9M, Gram = 0, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Herb Tea", Calorie = 6M, Carbonhydrade = 0.4M, Fat = 0M, Protein = 0M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Ice Tea", Calorie = 95M, Carbonhydrade = 22.3M, Fat = 0M, Protein = 0M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Lemon Lime Soda", Calorie = 125M, Carbonhydrade = 29.8M, Fat = 0M, Protein = 0.3M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Limeade", Calorie = 54M, Carbonhydrade = 16.6M, Fat = 0.6M, Protein = 0.9M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Malt Beverage", Calorie = 237M, Carbonhydrade = 19.2M, Fat = 0.4M, Protein = 0.5M, Gram = 0, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Milk", Calorie = 149M, Carbonhydrade = 10.9M, Fat = 8.4M, Protein = 7.6M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Milk, fat free", Calorie = 86M, Carbonhydrade = 11.9M, Fat = 0.4M, Protein = 8.3M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Milk, reduced fat", Calorie = 137M, Carbonhydrade = 13.5M, Fat = 4.9M, Protein = 9.7M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Milkshake", Calorie = 238M, Carbonhydrade = 38.3M, Fat = 5.6M, Protein = 6.3M, Gram = 0, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Orange Juice", Calorie = 99M, Carbonhydrade = 20.8M, Fat = 0.4M, Protein = 1.4M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Passion Fruit Juice", Calorie = 126M, Carbonhydrade = 33.6M, Fat = 0.1M, Protein = 1.0M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Peach Nectar", Calorie = 125M, Carbonhydrade = 29.7M, Fat = 1.3M, Protein = 0.5M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Pineapple Juice", Calorie = 133M, Carbonhydrade = 32.2M, Fat = 0.3M, Protein = 0.9M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Smoothie High Protein Creamy Chocolate, Slimfast", Calorie = 110M, Carbonhydrade = 2.1M, Fat = 3.5M, Protein = 12.0M, Gram = 0, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Sports Drink", Calorie = 28M, Carbonhydrade = 7.2M, Fat = 0M, Protein = 0M, Gram = 0, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Sprite", Calorie = 96M, Carbonhydrade = 20.3M, Fat = 0.1M, Protein = 0.1M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Tomato & Vegetable Juice", Calorie = 53M, Carbonhydrade = 11.1M, Fat = 0.2M, Protein = 1.5M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Vegetable & Fruit Juice", Calorie = 81M, Carbonhydrade = 10.1M, Fat = 0.5M, Protein = 0.1M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });
            meals.Add(new Meal() { MealName = "Vegetable Juice", Calorie = 53M, Carbonhydrade = 11.1M, Fat = 0.2M, Protein = 1.5M, Gram = 0, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.DrinkAndBeverages, ServiceType = ServiceType.Glass });

            meals.Add(new Meal() { MealName = "Bran Flakes", Calorie = 131M, Carbonhydrade = 32.2M, Fat = 0.8M, Protein = 4.0M, Gram = 40M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.BreakfastFoods, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Corn Flakes", Calorie = 108M, Carbonhydrade = 24.6M, Fat = 0.3M, Protein = 1.7M, Gram = 30M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.BreakfastFoods, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Egg, boiled", Calorie = 93M, Carbonhydrade = 0.7M, Fat = 6.4M, Protein = 7.5M, Gram = 50M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.BreakfastFoods, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Egg, dried", Calorie = 30M, Carbonhydrade = 0.1M, Fat = 2.2M, Protein = 2.4M, Gram = 50M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.BreakfastFoods, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Egg, raw", Calorie = 80M, Carbonhydrade = 0.4M, Fat = 5.3M, Protein = 7.0M, Gram = 50M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.BreakfastFoods, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Fruit Jam", Calorie = 56M, Carbonhydrade = 13.8M, Fat = 0.1M, Protein = 0.1M, Gram = 20M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.BreakfastFoods, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { Recipe = "Gluten Free Breakfast Granola \r\nMaterials: \r\n1/2 cup raw buckwheat \r\n1/2 cup of quinoa \r\n16-22 medium sized dates (core removed). \r\n3 tablespoons of coconut sugar \r\n1.5 tablespoons of chia seeds \r\n1/2 cup coconut powder \r\n3/2 glass of water \r\n1 teaspoon vanilla powder \r\n1/2 cup ground walnuts \r\n2 handfuls of hand-chopped walnuts \r\n3 tablespoons of cocoa powder \r\nWash the quinoa and buckwheat and soak them in water for 1 hour. Blend the dates, water and vanilla powder in a blender until you get a homogeneous consistency. Drain the quinoa and buckwheat. In a large bowl, mix quinoa, buckwheat, cocoa, chia seeds and coconut sugar. Add the coconut powder and walnuts. Add the date mixture and mix until all the ingredients are mixed together. Place a greaseproof paper on the baking tray and spread the mixture on the tray. Bake in the oven heated at 150°C for 45-50 minutes, stirring every 15 minutes. After the mixture has cooled, transfer it to a glass storage container. You can mix it with fresh fruits, yogurt or milk for your breakfast. Bon appetit!\r\n", MealName = "Gluten Free Breakfast Granola ", Calorie = 285M, Carbonhydrade = 29.8M, Fat = 14.5M, Protein = 8.1M, Gram = 70M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.BreakfastFoods, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { Recipe = "Gluten Free Pancakes \r\nMaterials: \r\n2 eggs \r\n1 glass of water Milk \r\n1 teaspoon of water \r\n1 teaspoon of baking powder \r\n1 pinch of salt \r\n1 cup gluten-free flour \r\n1 tablespoon of cornmeal \r\nPut all the ingredients in a large jar, close the lid and shake it. Pour the mixture, which has the consistency of boza, into the crepe pan that you have heated and oiled. Cook both sides of the pancake evenly. While eating the gluten-free crepe, you can fill it with jams that you prepared with reliable ingredients or you can choose it with breakfast items such as cheese and olives. Enjoy your meal!\r\n", MealName = "Gluten Free Pancakes ", Calorie = 200M, Carbonhydrade = 4.6M, Fat = 4.8M, Protein = 5.7M, Gram = 150M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.BreakfastFoods, ServiceType = ServiceType.Portion });

            meals.Add(new Meal() { MealName = "Green Olives", Calorie = 4M, Carbonhydrade = 0.1M, Fat = 0.4M, Protein = 0.1M, Gram = 3M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.BreakfastFoods, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Honey", Calorie = 64M, Carbonhydrade = 17.3M, Fat = 0M, Protein = 0.1M, Gram = 21M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.BreakfastFoods, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Muesli", Calorie = 124M, Carbonhydrade = 19.8M, Fat = 2.4M, Protein = 4.5M, Gram = 30M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.BreakfastFoods, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Olives", Calorie = 10M, Carbonhydrade = 0.5M, Fat = 0.9M, Protein = 0.1M, Gram = 9M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.BreakfastFoods, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Peanut Butter", Calorie = 88M, Carbonhydrade = 3.6M, Fat = 7.4M, Protein = 3.3M, Gram = 15M, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.BreakfastFoods, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Rolled Oats", Calorie = 39M, Carbonhydrade = 6.6M, Fat = 0.7M, Protein = 1.7M, Gram = 10M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.BreakfastFoods, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Tahini", Calorie = 86M, Carbonhydrade = 3.9M, Fat = 7.2M, Protein = 2.7M, Gram = 15M, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.BreakfastFoods, ServiceType = ServiceType.Portion });

            meals.Add(new Meal() { MealName = "Baked Beans", Calorie = 310M, Carbonhydrade = 43.3M, Fat = 10.3M, Protein = 11.1M, Gram = 200M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Beef Broth Soup", Calorie = 17M, Carbonhydrade = 0.1M, Fat = 0.5M, Protein = 2.7M, Gram = 240M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Biscuit with Egg", Calorie = 436M, Carbonhydrade = 35.4M, Fat = 25.3M, Protein = 17.4M, Gram = 145M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Burger", Calorie = 258M, Carbonhydrade = 26.5M, Fat = 10.4M, Protein = 14.7M, Gram = 99M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Cheese Pizza", Calorie = 278M, Carbonhydrade = 35.9M, Fat = 9.7M, Protein = 11.7M, Gram = 113M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Chicken Crispy Breast", Calorie = 375M, Carbonhydrade = 11.9M, Fat = 23.2M, Protein = 29.7M, Gram = 140M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Chicken Mushroom Soup", Calorie = 126M, Carbonhydrade = 15.1M, Fat = 6.1M, Protein = 2.0M, Gram = 126M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Chicken Pot Pie", Calorie = 598M, Carbonhydrade = 57.3M, Fat = 34.6M, Protein = 14.6M, Gram = 302M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Chicken Sandwich", Calorie = 468M, Carbonhydrade = 39.1M, Fat = 20.9M, Protein = 30.4M, Gram = 187M, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Chicken Soup", Calorie = 78M, Carbonhydrade = 1.9M, Fat = 2.6M, Protein = 11.1M, Gram = 252M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "French Fries", Calorie = 378M, Carbonhydrade = 49.8M, Fat = 18.1M, Protein = 4.0M, Gram = 117M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { Recipe = "Materials: \r\n1 package of gluten-free pasta \r\n1 zucchini \r\n1 eggplant \r\n1 bowl of white cheese \r\n1 cup of cherry tomatoes \r\n1 pinch of red pepper \r\n1-2 sprigs of fresh thyme \r\n1 pinch of salt \r\nOlive oil \r\nSlice the eggplant and zucchini into strips, sprinkle some water on the eggplants to remove the bitterness. Heat the grill pan and add 2 tablespoons of olive oil; Cook the zucchini and aubergines back and forth. Boil water in a deep saucepan and add the gluten-free pasta to the boiling water. Add the cherry tomatoes cut in half to the pan where you cooked the zucchini and eggplant. After the pasta softens, drain the water and put it in a separate pan with the cooked vegetables. Add salt, some olive oil and red pepper. After the pasta and vegetables are well mixed, put them on a plate; Serve with feta cheese and thyme. Enjoy your meal!\r\n", MealName = "Gluten Free Pasta ", Calorie = 250M, Carbonhydrade = 16M, Fat = 5.8M, Protein = 8.4M, Gram = 150M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { Recipe = "Gluten Free Pizza \r\nMaterials: \r\n2 cups gluten-free flour \r\n1 teaspoon salt \r\n1 egg \r\n1 teaspoon of water \r\n2 tablespoons of oil \r\n20 gr. Fresh yeast \r\n \r\nFor the top: \r\nTomato paste (may be homemade), mozzarella, pepper, mushrooms, olives, thyme, feta cheese. \r\nMix and knead the ingredients for the dough in a large bowl. Rest for 10 minutes. By placing the dough on the tray, expand it according to the size of the tray and the thickness of the dough you like. Let it rest for 30-45 minutes, thin the tomato paste with warm water and spread it on the dough. Place the ingredients on it and bake in the oven heated at 200°C for 20 minutes. You can serve gluten-free pizza without cooling.\r\n", MealName = "Gluten Free Pizza ", Calorie = 230M, Carbonhydrade = 25M, Fat = 4.9M, Protein = 5.9M, Gram = 110M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Gluten Free Vegetable Soup ", Calorie = 145M, Carbonhydrade = 23.8M, Fat = 3.8M, Protein = 6.0M, Gram = 250M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Gluten-Free Stuffed Meatballs ", Calorie = 250M, Carbonhydrade = 12M, Fat = 2.5M, Protein = 20.2M, Gram = 250M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Lasagna", Calorie = 166M, Carbonhydrade = 18.9M, Fat = 6.1M, Protein = 9.0M, Gram = 123M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Mushrooms", Calorie = 44M, Carbonhydrade = 8.3M, Fat = 0.7M, Protein = 3.4M, Gram = 156M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Omelet", Calorie = 94M, Carbonhydrade = 0.4M, Fat = 7.1M, Protein = 6.4M, Gram = 61M, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Pancakes", Calorie = 260M, Carbonhydrade = 45.4M, Fat = 7.0M, Protein = 4.1M, Gram = 116M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Pasta", Calorie = 301M, Carbonhydrade = 57.3M, Fat = 2.4M, Protein = 11.8M, Gram = 230M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Pasta with Tomato Sauce", Calorie = 176M, Carbonhydrade = 35.1M, Fat = 1.8M, Protein = 5.6M, Gram = 252M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Pizza", Calorie = 230M, Carbonhydrade = 30.3M, Fat = 8.2M, Protein = 10.8M, Gram = 109M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Rice Pilaf, cooked", Calorie = 352M, Carbonhydrade = 61.1M, Fat = 8.8M, Protein = 7.0M, Gram = 238M, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Rice Pilaf, raw", Calorie = 732M, Carbonhydrade = 155.7M, Fat = 2.8M, Protein = 21.3M, Gram = 204M, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Spaghetti with Meatballs", Calorie = 200M, Carbonhydrade = 22.9M, Fat = 8.2M, Protein = 8.7M, Gram = 200M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Sweet & Sour Chicken", Calorie = 46M, Carbonhydrade = 4.4M, Fat = 2.3M, Protein = 1.8M, Gram = 18.3M, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Tomato Soup", Calorie = 139M, Carbonhydrade = 22.6M, Fat = 3.3M, Protein = 6.3M, Gram = 252M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Tripe Soup", Calorie = 148M, Carbonhydrade = 8.1M, Fat = 5.2M, Protein = 17.2M, Gram = 200M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { Recipe = "Materials \r\n1 ½ tablespoons of butter \r\n1 ½ tablespoons gluten-free flour \r\n1 medium carrot \r\n1 medium zucchini \r\n15 green beans \r\n1 tablespoon of tomato paste \r\n5 cups of homemade chicken stock \r\nSalt, pepper, mint powder \r\nSlice the vegetables coarsely. Melt the butter and fry the gluten-free flour. Add tomato paste and vegetables. Finally, add the chicken broth and boil the vegetables. When the vegetables are soft, pass them through the blender, add the spices and bring to a boil. You can serve your soup hot. You can enjoy vegetable soup, which adds a new one to your gluten-free soup recipes. Enjoy your meal!\r\n", MealName = "Vegetable Soup", Calorie = 149M, Carbonhydrade = 26.3M, Fat = 3.8M, Protein = 6.0M, Gram = 252M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.VegatablesAndLegumes, ServiceType = ServiceType.Portion });

            meals.Add(new Meal() { MealName = "Bacon", Calorie = 106M, Carbonhydrade = 0.2M, Fat = 10.2M, Protein = 3.3M, Gram = 26M, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.MeatAndMeatProducts, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Chicken Nuggets", Calorie = 61M, Carbonhydrade = 3.0M, Fat = 4.1M, Protein = 3.2M, Gram = 20M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.MeatAndMeatProducts, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Chicken Tenders", Calorie = 81M, Carbonhydrade = 5.2M, Fat = 4.2M, Protein = 5.8M, Gram = 30M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.MeatAndMeatProducts, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Ham Salad", Calorie = 97M, Carbonhydrade = 4.8M, Fat = 7.0M, Protein = 3.9M, Gram = 45M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.MeatAndMeatProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Lamb Meat", Calorie = 678M, Carbonhydrade = 0M, Fat = 45M, Protein = 63.8M, Gram = 250M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.MeatAndMeatProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Poultry Salad", Calorie = 26M, Carbonhydrade = 1.0M, Fat = 1.8M, Protein = 1.5M, Gram = 13M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.MeatAndMeatProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Veal Bratwurst", Calorie = 286M, Carbonhydrade = 0.0M, Fat = 26.6M, Protein = 11.8M, Gram = 84M, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.MeatAndMeatProducts, ServiceType = ServiceType.Piece });


            meals.Add(new Meal() { MealName = "Egg Bread", Calorie = 115M, Carbonhydrade = 19.1M, Fat = 2.4M, Protein = 3.8M, Gram = 40M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.CerealsAndBreadProducts, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { MealName = "Frybread", Calorie = 502M, Carbonhydrade = 73.4M, Fat = 18.6M, Protein = 10.2M, Gram = 150M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.CerealsAndBreadProducts, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { Recipe = "Gluten Free Bagels \r\nMaterials: \r\n2 cups gluten-free flour \r\n1 cup of warm water \r\n5 g instant dry yeast \r\n1 tablespoon of granulated sugar \r\n1 tablespoon of margarine \r\n1/2 cup sesame seeds \r\nDissolve the yeast with warm milk, melt the margarine on the stove. Knead the gluten-free flour, yeast, granulated sugar and margarine together to form a soft dough. Cover the dough with a clean cloth and let it rest for 15 minutes. Break off small balls from the dough and roll them with your hands. Give the shape of a bagel by joining the ends of the roll. Dip the bagels first in warm water, then sesame seeds and place them on a baking tray with greaseproof paper. After keeping it like this for 1 hour, bake it in a preheated 200°C oven for 10-15 minutes. Your gluten free bagels are ready. You can serve it hot or warm. Enjoy your meal!\r\n", MealName = "Gluten Free Bagels ", Calorie = 290M, Carbonhydrade = 25.7M, Fat = 12.7M, Protein = 25.4M, Gram = 110M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.CerealsAndBreadProducts, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { Recipe = "Gluten Free Bread \r\nMaterials: \r\n· 2 glasses of gluten-free flour (options such as corn flour, rice flour, chickpea flour or gluten-free flour mixture can be preferred). \r\n1 teaspoon of salt \r\n3 teaspoons of fresh yeast \r\n· 2 tablespoons of oil \r\n2¼ glasses of warm water \r\nMix all the ingredients in a large bowl and blend until smooth. Shape the dough with your hands and place it in the greased bread pan or cake mold. Let it sit for 30 minutes to gain volume. Place the rested dough in the oven that you preheated at 200°C and bake for 20-25 minutes until the top is golden brown. When your bread is warm, you can serve it by slicing. Enjoy your meal!\r\n", MealName = "Gluten Free Bread ", Calorie = 71M, Carbonhydrade = 10.50M, Fat = 1M, Protein = 2.12M, Gram = 23M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.CerealsAndBreadProducts, ServiceType = ServiceType.Piece });

            meals.Add(new Meal() { MealName = "Wheat Bread", Calorie = 79M, Carbonhydrade = 13.8M, Fat = 1.3M, Protein = 3.1M, Gram = 30M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.CerealsAndBreadProducts, ServiceType = ServiceType.Piece });

            meals.Add(new Meal() { MealName = "Whole Wheat Bread", Calorie = 63M, Carbonhydrade = 10.68M, Fat = 1M, Protein = 2.55M, Gram = 25M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.CerealsAndBreadProducts, ServiceType = ServiceType.Piece });

            meals.Add(new Meal() { MealName = "Arugula", Calorie = 5M, Carbonhydrade = 0.7M, Fat = 0.1M, Protein = 0.5M, Gram = 20M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Salads, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Caesar Salad", Calorie = 94M, Carbonhydrade = 9.1M, Fat = 4.4M, Protein = 6.8M, Gram = 210M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Salads, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Caesar Salad with Chicken", Calorie = 349M, Carbonhydrade = 19.2M, Fat = 16.4M, Protein = 25.7M, Gram = 310M, GlutenRisk = GlutenRisk.LowRisk, MealCategories = MealCategories.Salads, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Coleslaw", Calorie = 292M, Carbonhydrade = 28.4M, Fat = 18.9M, Protein = 1.8M, Gram = 190M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Salads, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Cornsalad", Calorie = 12M, Carbonhydrade = 2.0M, Fat = 0.2M, Protein = 1.1M, Gram = 56M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Salads, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Iceberg Lettuce", Calorie = 8M, Carbonhydrade = 1.7M, Fat = 0.1M, Protein = 0.5M, Gram = 57M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Salads, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Potato Salad", Calorie = 358M, Carbonhydrade = 27.9M, Fat = 20.5M, Protein = 6.7M, Gram = 250M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Salads, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { MealName = "Vegetable Salad", Calorie = 22M, Carbonhydrade = 4.4M, Fat = 0.1M, Protein = 1.7M, Gram = 138M, GlutenRisk = GlutenRisk.None, MealCategories = MealCategories.Salads, ServiceType = ServiceType.Portion });

            meals.Add(new Meal() { AlternativeFoodID = 176, MealName = "White Bread", Calorie = 72M, Carbonhydrade = 13.62M, Fat = 1M, Protein = 2.55M, Gram = 25M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.CerealsAndBreadProducts, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { AlternativeFoodID = 175, MealName = "Bagel", Calorie = 325M, Carbonhydrade = 28.1M, Fat = 15.8M, Protein = 26.4M, Gram = 125M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.CerealsAndBreadProducts, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { AlternativeFoodID = 128, MealName = "Granola", Calorie = 293M, Carbonhydrade = 32.3M, Fat = 14.6M, Protein = 8.2M, Gram = 60M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.BreakfastFoods, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { AlternativeFoodID = 129, MealName = "Waffle", Calorie = 218M, Carbonhydrade = 24.7M, Fat = 10.6M, Protein = 5.9M, Gram = 100M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.BakeryProducts, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { AlternativeFoodID = 71, MealName = "Cake", Calorie = 352M, Carbonhydrade = 50.7M, Fat = 14.3M, Protein = 5.0M, Gram = 95M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.BakeryProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { AlternativeFoodID = 76, MealName = "Cheesecake", Calorie = 257M, Carbonhydrade = 20.4M, Fat = 18.0M, Protein = 4.4M, Gram = 80M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.BakeryProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { AlternativeFoodID = 75, MealName = "Brownie", Calorie = 243M, Carbonhydrade = 38.3M, Fat = 9.8M, Protein = 2.9M, Gram = 60M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.BakeryProducts, ServiceType = ServiceType.Portion });
            meals.Add(new Meal() { AlternativeFoodID = 176, MealName = "Oat Bran Bread", Calorie = 71M, Carbonhydrade = 11.9M, Fat = 1.3M, Protein = 3.1M, Gram = 30M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.CerealsAndBreadProducts, ServiceType = ServiceType.Piece });
            meals.Add(new Meal() { AlternativeFoodID = 176, MealName = "Rye Bread", Calorie = 83M, Carbonhydrade = 15.5M, Fat = 1.1M, Protein = 2.7M, Gram = 32M, GlutenRisk = GlutenRisk.HighRisk, MealCategories = MealCategories.CerealsAndBreadProducts, ServiceType = ServiceType.Piece });

            foreach (Meal meal in meals)
                context.Meals.Add(meal);
            base.Seed(context);

        }
    }
}
